### ISSUE TITLE
Please call `session.destroy_session()` when you're finished with the FxA session

### ISSUE THREAD

**Issue by rfk** [kewisch/pyamo#15]
In this function here:

  https://github.com/kewisch/pyamo/blob/master/pyamo/utils.py#L62

Please call `session.destroy_session()` when you're finished with it, to avoid leaving orphaned session tokens hanging around on the FxA server.

**Comment by kewisch** [comment]
Thanks for filing the issue. I've fixed this in mentioned commit and also adapted to the code mentioned in mozilla/PyFxA#51. It works like a charm!
