### ISSUE TITLE
Clarify about the API

### ISSUE THREAD

**Issue by KOLANICH** [kewisch/pyamo#16]
>This site doesn't have a services API, therefore these tools use website scraping to determine the right information and use the same endpoints as they would be used in the browser.

What are these then?

https://addons-server.readthedocs.io/en/latest/topics/api/index.html
https://gist.github.com/gregglind/8d381089191d58530222

**Comment by kewisch** [comment]
Ok, that quote is indeed not very elaborate. There are various APIs for addons. One is on services.addons.mozilla.org, which is the API mostly used by Firefox itself.

Then there is the new v3 API on addons.mozilla.org/api, which is still in development. Most of the commands for pyamo are meant to be used by add-on reviewers on addons.mozilla.org. The reviewers API is not very [feature rich](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html), and at the time this package was created the whole API did not exist yet. I'll slowly be migrating to the v3 API as soon as the endpoints I need is available. In fact, one of the v3 reviewers endpoints is recently being used in the admin commands.

Let me know if you have further questions

**Comment by KOLANICH** [comment]
Could you put the info (in the form of a table) about what is available (in services and in the lib) via API and what is available in the lib via scraping,  into readme?

**Comment by kewisch** [comment]
This is pretty much a moving target, so I haven't been adding any further information. Can you explain further what information you are looking to get out of it?
